source("scripts/uploader.R")
source("scripts/DESeq.R")
source("scripts/downloadDESeq.R")
# source("scripts/samplePCA.R")
# source("~/bin/felipeCommonFunctions/R/samplePCA.R")
library(shinydashboard)
library(DT)
library(shinyjs)
library(tidyverse)
library(magrittr)
library(felipeCommonFunctions)